### PR TITLE
hydra.sh: fix check for already-available docker image

### LINKED ISSUE #4783: Hydra tries to update docker image every single time
Every single time I run Hydra, it begins with:
```
Pull version v1.13 from Docker Hub...
v1.13: Pulling from scylladb/hydra
Digest: sha256:0629f8a22c712fbfde7ff889db6d75cee7e5d55b147b84ab89f6d6a1b1092fd6
Status: Image is up to date for scylladb/hydra:v1.13
docker.io/scylladb/hydra:v1.13
```

This check takes (on the office fast network) around 2.5 seconds.

Looking at the `docker/env/hydra.sh` script, it seems to have special code exactly to avoid this unnecessary update:
```base
if [[ ${USER} == "jenkins" || -z "`$tool images ${DOCKER_REPO}:${VERSION} -q`" ]]; then
    echo "Pull version $VERSION from Docker Hub..."
    $tool pull ${DOCKER_REPO}:${VERSION}
else
    echo "There is ${DOCKER_REPO}:${VERSION} in local cache, use it."
fi
```

But this code evidentally doesn't work.

The problem is that DOCKER_REPO is `docker.io/scylladb/hydra`, and should be just `scylladb/hydra`. With that change, everything seems to work - both the pull and the image check.

### PR DESCRIPTION
**Pull request by nyh**
Hydra has code to avoid even trying to pull the docker image if it
knows that the desired version is already available locally.
However, this check simply doesn't work -

It turns out that the syntax docker.io/scylladb/hydra works with
"docker pull" but not with "docker images". The syntax scylladb/hydra
works with both, so in this patch we switch to use it.

On my machine, this reduces "hydra" run time by about 2.5 seconds.

Fixes #4783

Signed-off-by: Nadav Har'El <nyh@scylladb.com>

### CODE REVIEW

**Comment by nyh** [comment]
As usual, my trivial patch failed the precommit test, but I don't understand why :-( The details link above https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-4784//workflow-stage seems to be green. Where are the errors?

File: docker/env/hydra.sh [hunk 1]
```diff
@@ -5,7 +5,7 @@ set -eo pipefail
 CMD=$@
 DOCKER_ENV_DIR=$(readlink -f "$0")
 DOCKER_ENV_DIR=$(dirname "${DOCKER_ENV_DIR}")
-DOCKER_REPO=docker.io/scylladb/hydra
+DOCKER_REPO=scylladb/hydra
```
Comment (k0machi) [inline docker/env/hydra.sh:8]: One issue with this change is that it seems this repo link was added in #4648 and changing it back might break the podman support.

Comment (nyh) [reply docker/env/hydra.sh:8]: So maybe we need the "docker.io" to be part of the "docker pull" command, not of DOCKER_REPO?
The command "docker images docker.io/scylladb/hydra" simply doesn't work.
I can try later to check whether my change works with podman, and if not, what does.

**Comment by k0machi** [comment]
Pre-commit problem is due to incorrect commit message tltle format:
```
18:33:07  ✖   subject may not be empty [subject-empty]
18:33:07  ✖   type may not be empty [type-empty]
18:33:07  ✖   scope may not be empty [scope-empty]
18:33:07  
18:33:07  ✖   found 3 problems, 0 warnings
18:33:07  ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
18:33:07  
```

File: docker/env/hydra.sh (hunk 1 above)
Comment (fruch) [reply docker/env/hydra.sh:8]: `podman images` does work with the full path

I think this should work:
```diff
diff --git i/docker/env/hydra.sh w/docker/env/hydra.sh
index c6708906..86e72ff0 100755
--- i/docker/env/hydra.sh
+++ w/docker/env/hydra.sh
@@ -5,7 +5,7 @@ set -eo pipefail
 CMD=$@
 DOCKER_ENV_DIR=$(readlink -f "$0")
 DOCKER_ENV_DIR=$(dirname "${DOCKER_ENV_DIR}")
-DOCKER_REPO=docker.io/scylladb/hydra
+DOCKER_REPO=scylladb/hydra
 SCT_DIR=$(dirname "${DOCKER_ENV_DIR}")
 SCT_DIR=$(dirname "${SCT_DIR}")
 VERSION=v$(cat "${DOCKER_ENV_DIR}/version")
@@ -157,6 +157,11 @@ elif which podman >/dev/null 2>&1 ; then
 else
   die "Please make sure you install either podman or docker on this machine to run hydra"
 fi
+is_podman="$($tool --help | { grep -o podman || :; })"
+
+if [ -z "$is_podman" ]; then
+  DOCKER_REPO="docker.io/$DOCKER_REPO"
+fi
 
 if [[ ${USER} == "jenkins" || -z "`$tool images ${DOCKER_REPO}:${VERSION} -q`" ]]; then
     echo "Pull version $VERSION from Docker Hub..."
@@ -198,7 +203,6 @@ AWS_OPTIONS=$(env | sed -n 's/^\(AWS_[^=]\+\)=.*/--env \1/p')
 # export all JENKINS_* env vars into the docker run
 JENKINS_OPTIONS=$(env | sed -n 's/^\(JENKINS_[^=]\+\)=.*/--env \1/p')
 
-is_podman="$($tool --help | { grep -o podman || :; })"
 docker_common_args=()
 
 function EPHEMERAL_PORT() {

```

I wrongly assume all the docker command are working with a full path like that.

**Comment by nyh** [comment]
Pushed new version where "docker pull" uses docker.io, but "docker images" doesn't. 
I tested the new script with both docker and podman, and verified that the image caching works as expected.

File: docker/env/hydra.sh (hunk 1 above)
Comment (nyh) [reply docker/env/hydra.sh:8]: I chose a simpler solution - we can use docker.io/.. just for the pull, and without the docker.io for all other uses - and it seems to work (I checked on both docker and podman).

**Review by k0machi — APPROVED** [review]

File: docker/env/hydra.sh [hunk 2]
```diff
@@ -160,9 +161,9 @@ fi
 
 if [[ ${USER} == "jenkins" || -z "`$tool images ${DOCKER_REPO}:${VERSION} -q`" ]]; then
     echo "Pull version $VERSION from Docker Hub..."
-    $tool pull ${DOCKER_REPO}:${VERSION}
+    $tool pull ${DOCKER_REGISTRY}/${DOCKER_REPO}:${VERSION}
```
Comment (fruch) [inline docker/env/hydra.sh:164]: This is not enough

Later there are more usages of the REPO, in the docker/podman run command run

**Review by fruch — CHANGES_REQUESTED** [review]
It's not enough to handle the `podman pull` only

File: docker/env/hydra.sh (hunk 2 above)
Comment (nyh) [reply docker/env/hydra.sh:164]: Why is it not enough? I tried it with podman, and it worked! Can you please try?
It seems that after you pulled the image, it's in the local cache and can be found without the registry.

Comment (fruch) [reply docker/env/hydra.sh:164]: seems that you are correct, couldn't understand why podman couldn't be aligned across all it's commands.

**Review by fruch — APPROVED** [review]
LGTM
